[general]
live_config_reload = true

[window]
blur = false
opacity = 1.0

[font]
# normal = { family = "Hurmit Nerd Font", style = "Regular" }
normal = { family = "ZedMono Nerd Font Mono", style = "Regular" }
# normal = { family = "JetBrains Mono Nerd Font", style = "Regular" }
size = 14

[scrolling]
multiplier = 20

[keyboard]
# bindings = [{ key = "2", mods = "Control", chars = "2" },]

# Colors (Kanagawa Dragon)
[colors.primary]
background = '#181616'
foreground = '#c5c9c5'

[colors.normal]
black = '#0d0c0c'
blue = '#8ba4b0'
cyan = '#8ea4a2'
green = '#8a9a7b'
magenta = '#a292a3'
red = '#c4746e'
white = '#C8C093'
yellow = '#c4b28a'

[colors.bright]
black = '#a6a69c'
blue = '#7FB4CA'
cyan = '#7AA89F'
green = '#87a987'
magenta = '#938AA9'
red = '#E46876'
white = '#c5c9c5'
yellow = '#E6C384'

[colors.selection]
background = '#2d4f67'
foreground = '#c8c093'

[[colors.indexed_colors]]
index = 16
color = '#ffa066'

[[colors.indexed_colors]]
index = 17
color = '#ff5d62'
